#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

type = "javascript"
account_id = "Pixeldrift00"
workers_dev = true

#[build]
#command = "./build.sh"
