name: Setup and Build
description: Generic setup action
inputs:
  node-version:
    required: false
    type: string
    default: '20.15.1'

runs:
  using: composite

  steps:

    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies and build project
      shell: bash
      run: |
        npm install
        npm run build
